"""API endpoints for user management, use case management and file processing done

Revision ID: 34728aaed0de
Revises: 20b4349c8832
Create Date: 2025-09-07 06:28:05.447243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34728aaed0de'
down_revision: Union[str, Sequence[str], None] = '20b4349c8832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_workflow_tracker',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('text_extraction', sa.String(length=50), nullable=True),
    sa.Column('requirement_generation', sa.String(length=50), nullable=True),
    sa.Column('scenario_generation', sa.String(length=50), nullable=True),
    sa.Column('test_case_generation', sa.String(length=50), nullable=True),
    sa.Column('test_data_generation', sa.String(length=50), nullable=True),
    sa.Column('test_script_generation', sa.String(length=50), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.file_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_workflow_tracker')
    # ### end Alembic commands ###
