"""remove_document_metadata_fields

Revision ID: 35f3230f928a
Revises: 8f4c767bf267
Create Date: 2025-09-26 15:36:44.029561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f3230f928a'
down_revision: Union[str, Sequence[str], None] = '8f4c767bf267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'document_type')
    op.drop_column('file_metadata', 'additional_context')
    op.drop_column('file_metadata', 'business_domain')
    op.drop_column('file_metadata', 'document_format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('document_format', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('file_metadata', sa.Column('business_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('file_metadata', sa.Column('additional_context', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('file_metadata', sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
