"""created usecase with chat, file_metadata and ocr_outputs tables for user ( changes reflected in env.py )

Revision ID: 6e0585d911c1
Revises: 8d0a24cf9670
Create Date: 2025-09-06 11:08:36.199310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0585d911c1'
down_revision: Union[str, Sequence[str], None] = '8d0a24cf9670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usecase_metadata',
    sa.Column('usecase_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('usecase_name', sa.String(), nullable=False),
    sa.Column('text_extraction', sa.String(length=50), nullable=True),
    sa.Column('requirement_generation', sa.String(length=50), nullable=True),
    sa.Column('scenario_generation', sa.String(length=50), nullable=True),
    sa.Column('test_case_generation', sa.String(length=50), nullable=True),
    sa.Column('test_script_generation', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('usecase_id')
    )
    op.create_table('file_metadata',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('usecase_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_link', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usecase_id'], ['usecase_metadata.usecase_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('ocr_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('completed_pages', sa.Integer(), nullable=False),
    sa.Column('error_pages', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.file_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_text', sa.Text(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.file_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_outputs')
    op.drop_table('ocr_info')
    op.drop_table('file_metadata')
    op.drop_table('usecase_metadata')
    # ### end Alembic commands ###
