"""created usecase with chat, file_metadata and ocr_outputs tables for user

Revision ID: 8d0a24cf9670
Revises: 42d93abd6407
Create Date: 2025-09-06 11:03:09.608670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0a24cf9670'
down_revision: Union[str, Sequence[str], None] = '42d93abd6407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
