"""Add OCR functionality with updated file metadata and workflow tracking

Revision ID: 8f4c767bf267
Revises: fcf081e7e26a
Create Date: 2025-09-26 13:02:37.133247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4c767bf267'
down_revision: Union[str, Sequence[str], None] = 'fcf081e7e26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('document_type', sa.String(length=255), nullable=True))
    op.add_column('file_metadata', sa.Column('document_format', sa.String(length=255), nullable=True))
    op.add_column('file_metadata', sa.Column('business_domain', sa.String(length=255), nullable=True))
    op.add_column('file_metadata', sa.Column('additional_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'additional_context')
    op.drop_column('file_metadata', 'business_domain')
    op.drop_column('file_metadata', 'document_format')
    op.drop_column('file_metadata', 'document_type')
    # ### end Alembic commands ###
