"""add_chat_summary_column_to_usecase_metadata

Revision ID: d1019ed7dbde
Revises: 35f3230f928a
Create Date: 2025-10-08 05:06:24.633412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1019ed7dbde'
down_revision: Union[str, Sequence[str], None] = '35f3230f928a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usecase_metadata', sa.Column('chat_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usecase_metadata', 'chat_summary')
    # ### end Alembic commands ###
