"""add status to usecase_metadata

Revision ID: fcf081e7e26a
Revises: 34728aaed0de
Create Date: 2025-09-18 11:56:28.803398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf081e7e26a'
down_revision: Union[str, Sequence[str], None] = '34728aaed0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usecase_metadata', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usecase_metadata', 'status')
    # ### end Alembic commands ###
